### ISSUE TITLE
adb_root does not enable adb root support on devices without adbd binary

### ISSUE THREAD

**Issue by SolidHal** [evdenis/adb_root#10]
seems devices like the samsung s20 lineup do not use a "usual" adbd binary in `/system/bin`
this results in adb root not working after installing this module

Wouldn't be surprised if https://github.com/evdenis/adb_root/issues/8 is related. 

Figured it might be some non-eng prop being set, so tried https://github.com/evdenis/enable_eng but that didn't work and actually broke the settings app as well?

Another guess I had was that selinux was causing issues, so I tried https://github.com/evdenis/selinux_permissive but that actually caused my device to boot loop. Seems samsung must have an additional check somewhere to make sure permissive is not set, as even running `su; setenforce 0` in `adb shell` causes the device to immediately crash and reboot.  

Poking around a stock system, I see the following adb related files that might be useful in figuring out what we need to swap out to actually get this working:
```
# find /system -name "*adbd*"
/system/lib64/libadbd_auth.so
/system/lib64/libadbd_fs.so
/system/apex/com.google.android.adbd.apex
/system/lib/libadbd_auth.so
/system/lib/libadbd_fs.so
```

I also read somewhere that `adbd` sometimes is present in the `boot.img` ramdisk but at least on my device this is not the case. 
To check on your own device, get the `boot.img` and run the following
```
abootimg -x boot.img
mkdir initrd; cd initrd
# you may need to be root to avoid permissions issues when extracting in the next step
su root
gunzip -c ../initrd.img | cpio -i
exit
find . -name "*adbd*"
```

**Comment by evdenis** [comment]
> seems devices like the samsung s20 lineup do not use a "usual" adbd binary in /system/bin

It's Android 11 changes. This module will not work on Android 11, (as for now, android 9/10 only). On Android 11 adbd is in /apex and Magisk doesn't provide easy ways to install binaries to /apex
