### ISSUE TITLE
unable to install the module

### ISSUE THREAD

**Issue by jstmeh** [evdenis/adb_root#7]
hello
when i select install from storage i cant select the adb_root.zip, however i can install other magisk zip modules

**Comment by evdenis** [comment]
Hi, what is you magisk version, firmware version, phone model?

**Comment by jstmeh** [comment]
thanks for reply,  i use custom rom from openkirin LineageOS 16.0 Build 6 it is Android 9

Magisk:
Latest     21.4 (21400) A/B No
Installed  21.4 (21400) SAR No

Manager 
Latest 8.0.7 (4834) (15)
Installed 8.0.7 (4834) (15)
Package uhoboh.rrytmphi

Device
Huawei mediapad m5 lite
model BAH2-l09

**Comment by jstmeh** [comment]
problem fixed, i had to change the directory to internal storage then browse to Download folders and i could click on the zip file
but still strange because i can click on and install magisk modules from the default first screen

here its not clickable, solution is to access internal storage and navigate to Download folder
https://drive.google.com/file/d/114yd4nhBoM-2ABERP_yYFCgS5lf2jMbT/view?usp=sharing

thanks, the problem solved and module working.

**Comment by evdenis** [comment]
Just to note, on Lineage there is a setting to run adbd daemon with root rights. Hence, this module is redundant.
